[package]
name = "simmis"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy", "serde"] }
thiserror = "2.0.18"

[dev-dependencies]
pretty_assertions = "1"
